### ISSUE TITLE
Invalid code source for camunda-bpm-camel-blueprint

### ISSUE THREAD

**Issue by wiax** [camunda/camunda-bpm-camel#17]
All java files in camunda-bpm-camel-blueprint are not subfixed by .java extension.

**Comment by meyerdan** [comment]
Hi @wiax, could you point us to an example where the file extension is wrong?

Daniel

**Comment by wiax** [comment]
Example of bad extension:  camunda-bpm-camel/camunda-bpm-camel-blueprint/src/main/java/org/camunda/bpm/camel/blueprint/CamelBlueprintELResolver (all the java files in the camunda-bpm-camel-blueprint).

Example of good extension:  camunda-bpm-camel/camunda-bpm-camel-common/src/main/java/org/camunda/bpm/camel/common/CamelService.java

**Comment by meyerdan** [comment]
Thanks!

@berndruecker  can you sort this out, please?

**Comment by berndruecker** [comment]
Thanks a lot for the pointer. If you want to get it fixes fast best send a pull request via GitHub. I added it to my list of stuff to do when there is a bit of time...

**Comment by berndruecker** [comment]
I renamed the files. I removed the test case as it doesn't test anything useful (so the component is untested at the moment!)
