### ISSUE TITLE
Samples Pages are Missing

### ISSUE THREAD

**Issue by apillai-incomm** [camunda/camunda-bpm-camel#46]
The Sample project links on pages are all leading to 404.

**Comment by berndruecker** [comment]
Can you send more details (which page are you refereing to and which links)? Thanks.

**Comment by apillai-incomm** [comment]
None of the Links on the Main Read Only page works. All the links including the Incubation page is going into 404. All the samples as well. These are basic stuff that leads to adoption of library. Hopefully this can be fixed.

**Comment by berndruecker** [comment]
I fixed one link "See example project 'camel use cases' for code for all of the use cases shown in the above model." on https://github.com/camunda/camunda-bpm-camel/blob/master/README.md. Thanks for reporting. 

If you know of more wrong links please let us now - but be more specific (URL to page, exact link text). Thanks!
