### ISSUE TITLE
can't catch BPMN error when camel throw exception

### ISSUE THREAD

**Issue by deniskru** [camunda/camunda-bpm-camel#47]
I have demo Spring Boot application with camunda-bpm-camel extention. Process starts normally , but I always get log normal step even camel throw exception. Boundary event never catch exception .  I expect log error step execution. What i'm doing wrong ? 
Versions 
`        <camunda.spring.boot.starter.version>3.0.0</camunda.spring.boot.starter.version>
        <spring.boot.version>2.0.2.RELEASE</spring.boot.version>
        <camunda.version>7.9.0</camunda.version>
        <camel.version>2.22.2</camel.version>
        <camunda.camel.version>0.7-SNAPSHOT</camunda.camel.version>
`
![default](https://user-images.githubusercontent.com/7669486/50550102-47c47680-0c9c-11e9-8568-378498bf7c50.PNG)
[https://github.com/deniskru/testCamelCamundaBoundary.git](url)

**Comment by berndruecker** [comment]
Hi @deniskru Sorry for not coming back to you earlier. Best ask in the http://forum.camunda.org/ to get a timely answer. Does the problem still persists? From a first glance it looks ok - so I also would need to try it out.

**Comment by berndruecker** [comment]
I close the issue for now - please reopen or better ask in the forum and share the link here
