### ISSUE TITLE
Support Camel 3

### ISSUE THREAD

**Issue by ninckblokje** [camunda/camunda-bpm-camel#53]
Hi,

Would you be willing to upgrade this project to Camel 3?

I am willing to provide a pull request with the required changes. I have already forked the repository and made the changes. But I need to test it before I can create the pull request.

Jeroen

**Comment by ninckblokje** [comment]
I have finished testing it, so I can create the pull request.

**Comment by berndruecker** [comment]
Hey @ninckblokje! Thanks for taking the effort and great to hear you succeeded so far :-) I have no idea what the changes required for Camel 3 are - also we are quite limited in time to support this from our end, even if "only" reviewing a pull request (to manage expectations!). But I would be happy to have a look at it. So can you open that PR or at least point me to your fork/branch where I can see what kind of changes (and how much) are necessary? That would be great, thanks.

**Comment by ninckblokje** [comment]
Mostly version upgrades. Added an @Autowired annotation and implemented close methods on the Camunda components.
