### ISSUE TITLE
Release 0.7

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-camel#57]
Changes:

- updated to Camel 3, Spring 5.2.x, Camunda 7.12, Powermock 2.x, Mockito 2.28.x
- Compiles also with Java >= 9
- Compile for Java 8

**Comment by berndruecker** [comment]
Passes build and tests: https://travis-ci.org/github/camunda/camunda-bpm-camel/builds/664381442

**Comment by ninckblokje** [comment]
Hi @berndruecker 

I tested the code and it worked (Java 11 + Camel 3)! I did notice that I was unable to compile the code with JDK 8, so I used JDK 11.

Jeroen

**Comment by ninckblokje** [comment]
Here is the error I got:

[INFO] Reactor Summary for camunda BPM - Apache Camel Integration 0.7-SNAPSHOT:
[INFO]
[INFO] camunda BPM - Apache Camel Integration ............. SUCCESS [  0.384 s]
[INFO] camunda BPM - Apache Camel Integration (Common) .... FAILURE [  2.463 s]
[INFO] camunda BPM - Apache Camel Integration (Common Test Resources) SKIPPED
[INFO] camunda BPM - Apache Camel Integration (Spring) .... SKIPPED
[INFO] camunda BPM - Apache Camel Integration (CDI) ....... SKIPPED
[INFO] camunda BPM - Apache Camel Integration (Blueprint) . SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.772 s
[INFO] Finished at: 2020-03-20T07:50:54+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project camunda-bpm-camel-common: Fatal error compiling: invalid flag: --release -> [Help 1]

**Comment by berndruecker** [comment]
Yes - this is to be expected - I introduced the new release flag which is only available from Java >= 9. But the resulting compiled artifact can run on Java 9

**Comment by berndruecker** [comment]
I just released a 0.7.0 version with the changes applied
